const onTimeResponses = [
    "Tao is here and ready to go!",
    "Tao is present and accounted for!",
    "Tao is in the house!",
    "Tao has arrived, let the fun begin!",
    "Tao reporting for duty!",
    "Tao is ready to tackle whatever comes their way!",
    "Tao is here, and they mean business!",
    "Tao has entered the chat, brace yourselves!",
    "Tao is ready to rock and roll!",
    "Tao is here to save the day!",
    "Tao has graced us with their presence!",
    "Tao is ready to take on the world!",
    "Tao is here, and they're not messing around!",
    "Tao has arrived, let the games begin!",
    "Tao is ready to show everyone who's boss!",
    "Tao is here, and they're ready to rumble!",
    "Tao has made their grand entrance!",
    "Tao is ready to take this to the next level!",
    "Tao is here, and they're not leaving until the job is done!",
    "Tao has arrived fashionably on time!",
    "Tao is ready to bring their A-game!",
    "Tao is here to shake things up!",
    "Tao has arrived, and they're ready to make a statement!",
    "Tao is ready to take charge and lead the way!",
    "Tao is here, and they're ready to make their mark!",
    "Tao has arrived, and they're not holding back!",
    "Tao is ready to show everyone what they're made of!",
    "Tao is here to take names and kick butt!",
    "Tao has arrived, and they're ready to steal the show!",
    "Tao is here, and they're ready to make a difference!"
];

const lateResponses = [
    "Tao is fashionably late, again, only ${noResponseCount} times so far.",
    "Tao took a nap and missed the roll call. That's ${noResponseCount} times since I've started counting.",
    "Tao was busy saving the world for the ${noResponseCount} time, but better late than never!",
    "Tao got lost on the way here, for the ${noResponseCount} time. Someone get them a map!",
    "Tao overslept and missed their alarm, again. That's ${noResponseCount} times and counting!",
    "Tao was caught up in an epic battle, but they've finally arrived, ${noResponseCount} times late!",
    "Tao took a detour to grab some coffee, for the ${noResponseCount} time. Can't blame them though!",
    "Tao got sidetracked by a shiny object, again. That's ${noResponseCount} times now!",
    "Tao was fashionably late to the party, as usual. We're up to ${noResponseCount} times!",
    "Tao got stuck in traffic, or so they claim. That's ${noResponseCount} excuses and counting!",
    "Tao was busy striking a heroic pose, for the ${noResponseCount} time. Priorities, right?",
    "Tao got lost in their own thoughts, again. That's ${noResponseCount} times they've zoned out!",
    "Tao was fashionably late, as per tradition. We're at ${noResponseCount} times and counting!",
    "Tao was busy saving a cat from a tree, allegedly. That's ${noResponseCount} heroic deeds!",
    "Tao got distracted by a butterfly, for the ${noResponseCount} time. It must have been a pretty butterfly!",
    "Tao was running on Tao Time, which is ${noResponseCount} times slower than regular time!",
    "Tao was busy being awesome, as usual. That's ${noResponseCount} times they've kept us waiting!",
    "Tao got sidetracked by a shiny pokemon, again. Gotta catch 'em all, even if it's ${noResponseCount} times!",
    "Tao was fashionably late, because they're just that cool. We're at ${noResponseCount} times now!",
    "Tao was busy saving the universe, or so they claim. That's ${noResponseCount} times they've used that excuse!",
    "Tao got lost in the space-time continuum, for the ${noResponseCount} time. Someone get them a flux capacitor!",
    "Tao was busy being a trendsetter, as usual. We're at ${noResponseCount} times fashionably late!",
    "Tao got distracted by a shiny object, again. That's ${noResponseCount} times they've been easily amused!",
    "Tao was running on Tao Standard Time, which is ${noResponseCount} times slower than regular time!",
    "Tao was busy being the life of the party, somewhere else. That's ${noResponseCount} times they've ditched us!",
    "Tao got sidetracked by a funny meme, for the ${noResponseCount} time. They just can't resist!",
    "Tao was fashionably late, because they like to keep us on our toes. We're at ${noResponseCount} times now!",
    "Tao was busy saving the world, one snooze button at a time. That's ${noResponseCount} times they've overslept!",
    "Tao got lost in their own awesomeness, again. That's ${noResponseCount} times they've been fashionably late!",
    "Tao was busy being a rebel, as usual. We're at ${noResponseCount} times fashionably late!"
];

module.exports = {
    onTimeResponses,
    lateResponses
};